// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("Agendamento")]
public partial class Agendamento
{
    [Key]
    [Column("IDAgendamento")]
    public int Idagendamento { get; set; }

    [Column("VeiculoID")]
    public int? VeiculoId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataHoraAgendada { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("VeiculoId")]
    [InverseProperty("Agendamentos")]
    public virtual Veiculo Veiculo { get; set; }
}