// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

public partial class cicero_injecao_eletronica_autocenter_Context : DbContext
{
    public cicero_injecao_eletronica_autocenter_Context(DbContextOptions<cicero_injecao_eletronica_autocenter_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Agendamento> Agendamentos { get; set; }

    public virtual DbSet<Categorium> Categoria { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Contato> Contatos { get; set; }

    public virtual DbSet<ControleDePermissao> ControleDePermissaos { get; set; }

    public virtual DbSet<CustoMaoDeObra> CustoMaoDeObras { get; set; }

    public virtual DbSet<DocumentoImagem> DocumentoImagems { get; set; }

    public virtual DbSet<FeedbackCliente> FeedbackCliente { get; set; }

    public virtual DbSet<Funcionario> Funcionarios { get; set; }

    public virtual DbSet<Pagamento> Pagamentos { get; set; }

    public virtual DbSet<PecaEmArmazem> PecaEmArmazems { get; set; }

    public virtual DbSet<PecaUtilizadum> PecaUtilizada { get; set; }

    public virtual DbSet<RelatorioEstatistica> RelatorioEstatisticas { get; set; }

    public virtual DbSet<Reparacao> Reparacaos { get; set; }

    public virtual DbSet<TempoMaoDeObra> TempoMaoDeObras { get; set; }

    public virtual DbSet<Veiculo> Veiculos { get; set; }
    public object Clientes { get; internal set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agendamento>(entity =>
        {
            entity.HasKey(e => e.Idagendamento).HasName("PK__Agendame__0530B6534B0BECA5");

            entity.Property(e => e.Idagendamento).ValueGeneratedNever();

            entity.HasOne(d => d.Veiculo).WithMany(p => p.Agendamentos).HasConstraintName("FK__Agendamen__Veicu__52593CB8");
        });

        modelBuilder.Entity<Categorium>(entity =>
        {
            entity.HasKey(e => e.IdCategoria).HasName("PK__Categori__8A3D240CB3AEE1BF");

            entity.Property(e => e.IdCategoria).ValueGeneratedNever();

            entity.HasOne(d => d.Cliente).WithMany(p => p.Categoria).HasConstraintName("FK__Categoria__Clien__3E52440B");

            entity.HasOne(d => d.Funcionario).WithMany(p => p.CategoriaNavigation).HasConstraintName("FK__Categoria__Funci__3F466844");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).HasName("PK__Cliente__71ABD0A7DD78F0A3");

            entity.Property(e => e.ClienteId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Contato>(entity =>
        {
            entity.HasKey(e => e.Idcliente).HasName("PK__Contatos__9B8553FCFCFB20E5");

            entity.Property(e => e.Idcliente).ValueGeneratedNever();

            entity.HasOne(d => d.IdclienteNavigation).WithOne(p => p.Contato)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contatos__IDClie__6477ECF3");

            entity.HasOne(d => d.IdfuncionarioNavigation).WithMany(p => p.Contatos).HasConstraintName("FK__Contatos__IDFunc__656C112C");
        });

        modelBuilder.Entity<ControleDePermissao>(entity =>
        {
            entity.HasKey(e => e.Idfuncionario).HasName("PK__Controle__3E1A7BE7D6E902F5");

            entity.Property(e => e.Idfuncionario).ValueGeneratedNever();

            entity.HasOne(d => d.IdfuncionarioNavigation).WithOne(p => p.ControleDePermissao)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ControleD__IDFun__5BE2A6F2");
        });

        modelBuilder.Entity<CustoMaoDeObra>(entity =>
        {
            entity.HasKey(e => e.IdCustoMaoDeObra).HasName("PK__CustoMao__C4A8707182C409BC");

            entity.Property(e => e.IdCustoMaoDeObra).ValueGeneratedNever();
        });

        modelBuilder.Entity<DocumentoImagem>(entity =>
        {
            entity.HasKey(e => e.IddocumentoImagem).HasName("PK__Document__DABACAA2E4D34C8F");

            entity.Property(e => e.IddocumentoImagem).ValueGeneratedNever();

            entity.HasOne(d => d.IdveiculoNavigation).WithMany(p => p.DocumentoImagems).HasConstraintName("FK__Documento__IDVei__5EBF139D");
        });

        modelBuilder.Entity<FeedbackCliente>(entity =>
        {
            entity.HasKey(e => e.Idfeedback).HasName("PK__Feedback__8456A50A0B80CE4C");

            entity.Property(e => e.Idfeedback).ValueGeneratedNever();

            entity.HasOne(d => d.IdclienteNavigation).WithMany(p => p.FeedbackClientes).HasConstraintName("FK__FeedbackC__IDCli__59063A47");
        });

        modelBuilder.Entity<Funcionario>(entity =>
        {
            entity.HasKey(e => e.FuncionarioId).HasName("PK__Funciona__297ECD4AE381FA7D");

            entity.Property(e => e.FuncionarioId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Pagamento>(entity =>
        {
            entity.HasKey(e => e.Idpagamento).HasName("PK__Pagament__984849FE90127915");

            entity.Property(e => e.Idpagamento).ValueGeneratedNever();

            entity.HasOne(d => d.FuncionarioNavigation).WithMany(p => p.Pagamentos).HasConstraintName("FK__Pagamento__Funci__5629CD9C");

            entity.HasOne(d => d.IdveiculoNavigation).WithMany(p => p.Pagamentos).HasConstraintName("FK__Pagamento__IDVei__5535A963");
        });

        modelBuilder.Entity<PecaEmArmazem>(entity =>
        {
            entity.HasKey(e => e.PecaEmArmazemId).HasName("PK__PecaEmAr__EA61BAF25260E07F");

            entity.Property(e => e.PecaEmArmazemId).ValueGeneratedNever();

            entity.HasOne(d => d.Peca).WithMany(p => p.PecaEmArmazems).HasConstraintName("FK__PecaEmArm__PecaI__4F7CD00D");
        });

        modelBuilder.Entity<PecaUtilizadum>(entity =>
        {
            entity.HasKey(e => e.PecaId).HasName("PK__PecaUtil__FE5BE67C746C357D");

            entity.Property(e => e.PecaId).ValueGeneratedNever();

            entity.HasOne(d => d.Reparacao).WithMany(p => p.PecaUtilizada).HasConstraintName("FK__PecaUtili__Repar__48CFD27E");
        });

        modelBuilder.Entity<RelatorioEstatistica>(entity =>
        {
            entity.HasKey(e => e.Idregistro).HasName("PK__Relatori__DFE4ED54C6A9FE7F");

            entity.Property(e => e.Idregistro).ValueGeneratedNever();

            entity.HasOne(d => d.IdpagamentoNavigation).WithMany(p => p.RelatorioEstatisticas).HasConstraintName("FK__Relatorio__IDPag__619B8048");
        });

        modelBuilder.Entity<Reparacao>(entity =>
        {
            entity.HasKey(e => e.ReparacaoId).HasName("PK__Reparaca__B198A750C2E91609");

            entity.Property(e => e.ReparacaoId).ValueGeneratedNever();

            entity.HasOne(d => d.Cliente).WithMany(p => p.Reparacaos).HasConstraintName("FK__Reparacao__Clien__45F365D3");

            entity.HasOne(d => d.Veiculo).WithMany(p => p.Reparacaos).HasConstraintName("FK__Reparacao__Veicu__44FF419A");
        });

        modelBuilder.Entity<TempoMaoDeObra>(entity =>
        {
            entity.HasKey(e => e.TempoMaoDeObraId).HasName("PK__TempoMao__C9B6FE2B4B33B6C5");

            entity.Property(e => e.TempoMaoDeObraId).ValueGeneratedNever();

            entity.HasOne(d => d.Funcionario).WithMany(p => p.TempoMaoDeObras).HasConstraintName("FK__TempoMaoD__Funci__4CA06362");

            entity.HasOne(d => d.Reparacao).WithMany(p => p.TempoMaoDeObras).HasConstraintName("FK__TempoMaoD__Repar__4BAC3F29");
        });

        modelBuilder.Entity<Veiculo>(entity =>
        {
            entity.HasKey(e => e.VeiculoId).HasName("PK__Veiculo__A5253AD8CEED1D75");

            entity.Property(e => e.VeiculoId).ValueGeneratedNever();

            entity.HasOne(d => d.Cliente).WithMany(p => p.Veiculos).HasConstraintName("FK__Veiculo__Cliente__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}