// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("Cliente")]
public partial class Cliente
{
    internal readonly object ClienteID;

    [Key]
    [Column("ClienteID")]
    public int ClienteId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    public DateOnly? DataNascimento { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Genero { get; set; }

    [Column("CPF")]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstadoCivil { get; set; }

    [Unicode(false)]
    public string Observacao { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<Categorium> Categoria { get; set; } = new List<Categorium>();

    [InverseProperty("IdclienteNavigation")]
    public virtual Contato Contato { get; set; }

    [InverseProperty("IdclienteNavigation")]
    public virtual ICollection<FeedbackCliente> FeedbackClientes { get; set; } = new List<FeedbackCliente>();

    [InverseProperty("Cliente")]
    public virtual ICollection<Reparacao> Reparacaos { get; set; } = new List<Reparacao>();

    [InverseProperty("Cliente")]
    public virtual ICollection<Veiculo> Veiculos { get; set; } = new List<Veiculo>();
}