// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("ControleDePermissao")]
public partial class ControleDePermissao
{
    [Key]
    [Column("IDFuncionario")]
    public int Idfuncionario { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NomeDoUsuario { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Cargo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NomeDeUsuario { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NivelDeAcesso { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Departamento { get; set; }

    [Column("DataEHoraDeAcesso", TypeName = "datetime")]
    public DateTime? DataEhoraDeAcesso { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OperacoesRealizadas { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ResultadoDaOperacao { get; set; }

    [Column("IPDeAcesso")]
    [StringLength(255)]
    [Unicode(false)]
    public string IpdeAcesso { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string AcaoDeBloqueio { get; set; }

    [Unicode(false)]
    public string Observacoes { get; set; }

    [ForeignKey("Idfuncionario")]
    [InverseProperty("ControleDePermissao")]
    public virtual Funcionario IdfuncionarioNavigation { get; set; }
}