// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

public partial class Contato
{
    [Key]
    [Column("IDCliente")]
    public int Idcliente { get; set; }

    [Column("IDFuncionario")]
    public int? Idfuncionario { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Morada { get; set; }

    [ForeignKey("Idcliente")]
    [InverseProperty("Contato")]
    public virtual Cliente IdclienteNavigation { get; set; }

    [ForeignKey("Idfuncionario")]
    [InverseProperty("Contatos")]
    public virtual Funcionario IdfuncionarioNavigation { get; set; }
}