// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("DocumentoImagem")]
public partial class DocumentoImagem
{
    [Key]
    [Column("IDDocumentoImagem")]
    public int IddocumentoImagem { get; set; }

    [Column("IDVeiculo")]
    public int? Idveiculo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NomeArquivo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string TipoDocumentoImagem { get; set; }

    public DateOnly? DataEnvioCriacao { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Unicode(false)]
    public string Arquivo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("Idveiculo")]
    [InverseProperty("DocumentoImagems")]
    public virtual Veiculo IdveiculoNavigation { get; set; }
}