// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("FeedbackCliente")]
public partial class FeedbackCliente
{
    [Key]
    [Column("IDFeedback")]
    public int Idfeedback { get; set; }

    [Column("IDCliente")]
    public int? Idcliente { get; set; }

    [Column("DataEHora", TypeName = "datetime")]
    public DateTime? DataEhora { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Avaliacoes { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Comentario { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ServicoAvaliado { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RespostaDaOficina { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string StatusDoFeedback { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CanalDoFeedback { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AcaoTomada { get; set; }

    [ForeignKey("Idcliente")]
    [InverseProperty("FeedbackClientes")]
    public virtual Cliente IdclienteNavigation { get; set; }
}