// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("Funcionario")]
public partial class Funcionario
{
    [Key]
    [Column("FuncionarioID")]
    public int FuncionarioId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Categoria { get; set; }

    public DateOnly? DataContratacao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Salario { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ContatoEmergencia { get; set; }

    [Unicode(false)]
    public string Qualificacoes { get; set; }

    [InverseProperty("Funcionario")]
    public virtual ICollection<Categorium> CategoriaNavigation { get; set; } = new List<Categorium>();

    [InverseProperty("IdfuncionarioNavigation")]
    public virtual ICollection<Contato> Contatos { get; set; } = new List<Contato>();

    [InverseProperty("IdfuncionarioNavigation")]
    public virtual ControleDePermissao ControleDePermissao { get; set; }

    [InverseProperty("FuncionarioNavigation")]
    public virtual ICollection<Pagamento> Pagamentos { get; set; } = new List<Pagamento>();

    [InverseProperty("Funcionario")]
    public virtual ICollection<TempoMaoDeObra> TempoMaoDeObras { get; set; } = new List<TempoMaoDeObra>();
}