// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("PecaEmArmazem")]
public partial class PecaEmArmazem
{
    [Key]
    [Column("PecaEmArmazemID")]
    public int PecaEmArmazemId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CodigoPeca { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? CustoUnitario { get; set; }

    public int? QuantidadeAtual { get; set; }

    [Column("PecaID")]
    public int? PecaId { get; set; }

    [ForeignKey("PecaId")]
    [InverseProperty("PecaEmArmazems")]
    public virtual PecaUtilizadum Peca { get; set; }
}