// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

public partial class PecaUtilizadum
{
    [Key]
    [Column("PecaID")]
    public int PecaId { get; set; }

    [Column("ReparacaoID")]
    public int? ReparacaoId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CodigoPeca { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Designacao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? PrecoUnitario { get; set; }

    public int? Quantidade { get; set; }

    [InverseProperty("Peca")]
    public virtual ICollection<PecaEmArmazem> PecaEmArmazems { get; set; } = new List<PecaEmArmazem>();

    [ForeignKey("ReparacaoId")]
    [InverseProperty("PecaUtilizada")]
    public virtual Reparacao Reparacao { get; set; }
}