// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("Reparacao")]
public partial class Reparacao
{
    [Key]
    [Column("ReparacaoID")]
    public int ReparacaoId { get; set; }

    [Column("VeiculoID")]
    public int? VeiculoId { get; set; }

    [Column("ClienteID")]
    public int? ClienteId { get; set; }

    public DateOnly? DataReparacao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? CustoTotal { get; set; }

    [Unicode(false)]
    public string Descricao { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Unicode(false)]
    public string Observacoes { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Reparacaos")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("Reparacao")]
    public virtual ICollection<PecaUtilizadum> PecaUtilizada { get; set; } = new List<PecaUtilizadum>();

    [InverseProperty("Reparacao")]
    public virtual ICollection<TempoMaoDeObra> TempoMaoDeObras { get; set; } = new List<TempoMaoDeObra>();

    [ForeignKey("VeiculoId")]
    [InverseProperty("Reparacaos")]
    public virtual Veiculo Veiculo { get; set; }
    public object TempoMaoDeOb { get; internal set; }
}