// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("TempoMaoDeObra")]
public partial class TempoMaoDeObra
{
    [Key]
    [Column("TempoMaoDeObraID")]
    public int TempoMaoDeObraId { get; set; }

    [Column("ReparacaoID")]
    public int? ReparacaoId { get; set; }

    [Column("FuncionarioID")]
    public int? FuncionarioId { get; set; }

    public int? TempoGasto { get; set; }

    [ForeignKey("FuncionarioId")]
    [InverseProperty("TempoMaoDeObras")]
    public virtual Funcionario Funcionario { get; set; }

    [ForeignKey("ReparacaoId")]
    [InverseProperty("TempoMaoDeObras")]
    public virtual Reparacao Reparacao { get; set; }
}