// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cicero_autocenterAPI.Models;

[Table("Veiculo")]
public partial class Veiculo
{
    [Key]
    [Column("VeiculoID")]
    public int VeiculoId { get; set; }

    [Column("ClienteID")]
    public int? ClienteId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Modelo { get; set; }

    public short? AnoFabricacao { get; set; }

    [StringLength(17)]
    [Unicode(false)]
    public string Chassi { get; set; }

    public int? Quilometragem { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string Placa { get; set; }

    public DateOnly? DataAquisicao { get; set; }

    [InverseProperty("Veiculo")]
    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();

    [ForeignKey("ClienteId")]
    [InverseProperty("Veiculos")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("IdveiculoNavigation")]
    public virtual ICollection<DocumentoImagem> DocumentoImagems { get; set; } = new List<DocumentoImagem>();

    [InverseProperty("IdveiculoNavigation")]
    public virtual ICollection<Pagamento> Pagamentos { get; set; } = new List<Pagamento>();

    [InverseProperty("Veiculo")]
    public virtual ICollection<Reparacao> Reparacaos { get; set; } = new List<Reparacao>();
}